
beetl:
    # 修改beetlmob的后缀,默认后缀是btl
    suffix: html
    #MVC视图模板后缀路径, ajax异步请求,不然找不到模板 404
    templatesViewSuffix: 
beetlsql:
    basePackage: com.d7kj.dao
    dbStyle: org.beetl.sql.core.db.PostgresStyle
    sqlPath: /sql    
beetl-beetlsql:
    dev: true

# 启用所有监控
endpoints:
    default:
        web:
            enabled: true
            
# http://localhost:8081/manage/health    
management:
    endpoints:
        web:
            base-path: /manage
    server:
        port: 8081
               
query:
    all: fuck
    
# web 服务器端口
server:
    port: 80        
        
spring:
    # 数据源
    datasource:
        # mysql
        url: jdbc:mysql://127.0.0.1:3306/orm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        #url: jdbc:mysql://192.168.0.6:3306/orm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
        #driver-class-name: com.mysql.jdbc.Driver
        #postgresql
        platform: postgres
        #url: jdbc:postgresql://192.168.0.3:5432/postgres
        #username: postgres
        #password: mypwd
        #driver-class-name: org.postgresql.Driver
        
    # spring data jpa 打印sql语句
    jpa: 
        show-sql: true

    redis:
        host: 127.0.0.1
        #password: 123456
        #port: 6379
        pool:
            max-active: 8
    servlet:
        # 文件上传
        # 文件保存的路径
        multipart:
            location: d:/
