
beetl:
    # 修改beetlmob的后缀,默认后缀是btl
    suffix: html
    #MVC视图模板后缀路径, ajax异步请求,不然找不到模板 404
    templatesViewSuffix: 
beetlsql:
    basePackage: com.d7kj.dao
    dbStyle: org.beetl.sql.core.db.MySqlStyle
    #dbStyle: org.beetl.sql.core.db.PostgresStyle
    daoSuffix: Dao
    nameConversion: org.beetl.sql.core.UnderlinedNameConversion
    sqlPath: /sql    
beetl-beetlsql:
    # 打印 SQL
    dev: true

# 启用所有监控
endpoints:
    default:
        web:
            enabled: true

logging:
    file:
        path: my.log
    level:
        root: info
        com.d7kj: debug
    pattern:
        #console: %level %date{HH:mm:ss} %logger{20}.%M %L :%m%n
        #file: %level %date{ISO8601} [%thread] %logger{20}.%M %L :%m%n

# http://localhost:8081/manage/health    
management:
    endpoints:
        web:
            base-path: /manage
    server:
        port: 8081
               
query:
    all: fuck
    
# web 服务器端口
server:
    port: 80        
    undertow:
        accesslog:
            enabled: true
            dir: undertow-logs
        io-threads: 8
        #max-http-post-size: 0
        worker-threads: 8
        
spring:
    # 数据源
    datasource:
        # mysql
        url: jdbc:mysql://127.0.0.1:3306/orm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        #url: jdbc:mysql://192.168.0.6:3306/orm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
        username: root
        password: 123456
        #driver-class-name: com.mysql.jdbc.Driver
        #postgresql
        platform: postgres
        #url: jdbc:postgresql://192.168.0.3:5432/postgres
        #username: postgres
        #password: mypwd
        #driver-class-name: org.postgresql.Driver
        
    # spring data jpa 打印sql语句
    jpa:
        hibernate:
            # 自动建库
            ddl-auto: update
        # 打印SQL 语句
        show-sql: true

    redis:
        host: 127.0.0.1
        #password: 123456
        #port: 6379
        pool:
            max-active: 8
    servlet:
        # 文件上传
        multipart:
            enabled: true
            file-size-threshold: 0
            # 文件保存的路径
            location: d:/
            max-file-size: 1MB
            max-request-size: 10MB
            resolve-lazily: false

